In [1]:
import pandas as pd

# Load the JSON file into a pandas DataFrame
df = pd.read_json('small_file_aa.json', lines=True)

In [2]:
df.columns

Index(['id', 'submitter', 'authors', 'title', 'comments', 'journal-ref', 'doi',
       'report-no', 'categories', 'license', 'abstract', 'versions',
       'update_date', 'authors_parsed'],
      dtype='object')

In [3]:
df.head()

,id,submitter,authors,title,comments,journal-ref,doi,report-no,categories,license,abstract,versions,update_date,authors_parsed
0,704.0001,Pavel Nadolsky,"C. Bal\'azs, E. L. Berger, P. M. Nadolsky, C.-...",Calculation of prompt diphoton production cros...,"37 pages, 15 figures; published version","Phys.Rev.D76:013009,2007",10.1103/PhysRevD.76.013009,ANL-HEP-PR-07-12,hep-ph,None,A fully differential calculation in perturba...,"[{'version': 'v1', 'created': 'Mon, 2 Apr 2007...",2008-11-26,"[[Balázs, C., ], [Berger, E. L., ], [Nadolsky,..."
1,704.0002,Louis Theran,Ileana Streinu and Louis Theran,Sparsity-certifying Graph Decompositions,To appear in Graphs and Combinatorics,None,None,None,math.CO cs.CG,http://arxiv.org/licenses/nonexclusive-distrib...,"We describe a new algorithm, the $(k,\ell)$-...","[{'version': 'v1', 'created': 'Sat, 31 Mar 200...",2008-12-13,"[[Streinu, Ileana, ], [Theran, Louis, ]]"
2,704.0003,Hongjun Pan,Hongjun Pan,The evolution of the Earth-Moon system based o...,"23 pages, 3 figures",None,None,None,physics.gen-ph,None,The evolution of Earth-Moon system is descri...,"[{'version': 'v1', 'created': 'Sun, 1 Apr 2007...",2008-01-13,"[[Pan, Hongjun, ]]"
3,704.0004,David Callan,David Callan,A determinant of Stirling cycle numbers counts...,11 pages,None,None,None,math.CO,None,We show that a determinant of Stirling cycle...,"[{'version': 'v1', 'created': 'Sat, 31 Mar 200...",2007-05-23,"[[Callan, David, ]]"
4,704.0005,Alberto Torchinsky,Wael Abu-Shammala and Alberto Torchinsky,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,None,"Illinois J. Math. 52 (2008) no.2, 681-689",None,None,math.CA math.FA,None,In this paper we show how to compute the $\L...,"[{'version': 'v1', 'created': 'Mon, 2 Apr 2007...",2013-10-15,"[[Abu-Shammala, Wael, ], [Torchinsky, Alberto, ]]"

In [4]:
df.iloc[55000, ].versions

[{'version': 'v1', 'created': 'Fri, 21 Mar 2008 23:11:46 GMT'},
 {'version': 'v2', 'created': 'Fri, 16 May 2008 23:46:33 GMT'}]

In [5]:
df[df['comments'] != None]

,id,submitter,authors,title,comments,journal-ref,doi,report-no,categories,license,abstract,versions,update_date,authors_parsed
0,704.0001,Pavel Nadolsky,"C. Bal\'azs, E. L. Berger, P. M. Nadolsky, C.-...",Calculation of prompt diphoton production cros...,"37 pages, 15 figures; published version","Phys.Rev.D76:013009,2007",10.1103/PhysRevD.76.013009,ANL-HEP-PR-07-12,hep-ph,None,A fully differential calculation in perturba...,"[{'version': 'v1', 'created': 'Mon, 2 Apr 2007...",2008-11-26,"[[Balázs, C., ], [Berger, E. L., ], [Nadolsky,..."
1,704.0002,Louis Theran,Ileana Streinu and Louis Theran,Sparsity-certifying Graph Decompositions,To appear in Graphs and Combinatorics,None,None,None,math.CO cs.CG,http://arxiv.org/licenses/nonexclusive-distrib...,"We describe a new algorithm, the $(k,\ell)$-...","[{'version': 'v1', 'created': 'Sat, 31 Mar 200...",2008-12-13,"[[Streinu, Ileana, ], [Theran, Louis, ]]"
2,704.0003,Hongjun Pan,Hongjun Pan,The evolution of the Earth-Moon system based o...,"23 pages, 3 figures",None,None,None,physics.gen-ph,None,The evolution of Earth-Moon system is descri...,"[{'version': 'v1', 'created': 'Sun, 1 Apr 2007...",2008-01-13,"[[Pan, Hongjun, ]]"
3,704.0004,David Callan,David Callan,A determinant of Stirling cycle numbers counts...,11 pages,None,None,None,math.CO,None,We show that a determinant of Stirling cycle...,"[{'version': 'v1', 'created': 'Sat, 31 Mar 200...",2007-05-23,"[[Callan, David, ]]"
4,704.0005,Alberto Torchinsky,Wael Abu-Shammala and Alberto Torchinsky,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,None,"Illinois J. Math. 52 (2008) no.2, 681-689",None,None,math.CA math.FA,None,In this paper we show how to compute the $\L...,"[{'version': 'v1', 'created': 'Mon, 2 Apr 2007...",2013-10-15,"[[Abu-Shammala, Wael, ], [Torchinsky, Alberto, ]]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,1103.2727,Giulia Pancheri Dr.,Luisa Bonolis and Giulia Pancheri,Bruno Touschek: particle physicist and father ...,To be published in EPJH,"Eur.Phys.J.H36:1-61,2011",10.1140/epjh/e2011-10044-1,"MIT-CTP 4212, LNF-11/01(P)",physics.hist-ph,http://arxiv.org/licenses/nonexclusive-distrib...,This article gives a brief outline of the li...,"[{'version': 'v1', 'created': 'Mon, 14 Mar 201...",2015-03-19,"[[Bonolis, Luisa, ], [Pancheri, Giulia, ]]"
249996,1103.2728,Sam Waldman,S. J. Waldman (the LIGO Scientific Collaboration),The Advanced LIGO Gravitational Wave Detector,This paper was originally prepared for the pro...,None,None,LIGO P0900115-v2,gr-qc,http://arxiv.org/licenses/nonexclusive-distrib...,The Advanced LIGO gravitational wave detecto...,"[{'version': 'v1', 'created': 'Mon, 14 Mar 201...",2011-03-15,"[[Waldman, S. J., , the LIGO Scientific Collab..."
249997,1103.2729,Zhu Wang,Traian iliescu and Zhu Wang,Variational Multiscale Proper Orthogonal Decom...,"22 pages, 4 figures",None,None,None,math.NA,http://arxiv.org/licenses/nonexclusive-distrib...,We introduce a variational multiscale closur...,"[{'version': 'v1', 'created': 'Mon, 14 Mar 201...",2015-03-19,"[[iliescu, Traian, ], [Wang, Zhu, ]]"
249998,1103.2730,P. S. Howe,J. Greitz and P.S. Howe,Maximal supergravity in three dimensions: supe...,27 pages. Small changes to the text; added ref...,"JHEP 1107:071,2011",10.1007/JHEP07(2011)071,KCL-MTH-11-07,hep-th,http://arxiv.org/licenses/nonexclusive-distrib...,The maximal supergravity theory in three dim...,"[{'version': 'v1', 'created': 'Mon, 14 Mar 201...",2011-07-21,"[[Greitz, J., ], [Howe, P. S., ]]"
249999,1103.2731,Vincent Pilaud,Vincent Pilaud and Francisco Santos,The brick polytope of a sorting network,"36 pages, 25 figures; Version 2 refers to the ...","European J. Combin., 33(4):632-662, 2012",10.1016/j.ejc.2011.12.003,None,math.CO math.MG,http://arxiv.org/licenses/nonexclusive-distrib...,The associahedron is a polytope whose graph ...,"[{'version': 'v1', 'created': 'Mon, 14 Mar 201...",2013-10-29,"[[Pilaud, Vincent, ], [Santos, Francisco, ]]"

In [6]:
df[df['title'].str.split().str.len() < 2]

,id,submitter,authors,title,comments,journal-ref,doi,report-no,categories,license,abstract,versions,update_date,authors_parsed
1378,704.1379,Michael Mayer,"Wei Lao, Michael Mayer",U-max-Statistics,16 pages,None,None,None,math.ST math.PR stat.TH,None,"In 1948, W. Hoeffding introduced a large cla...","[{'version': 'v1', 'created': 'Wed, 11 Apr 200...",2007-05-23,"[[Lao, Wei, ], [Mayer, Michael, ]]"
6895,705.2893,Luis Raul Abramo,L. Raul Abramo and Patrick Peter,K-Bounce,Replaced with version accepted to JCAP,"JCAP0709:001,2007",10.1088/1475-7516/2007/09/001,None,astro-ph gr-qc hep-th,None,By demanding that a bounce is nonsingular an...,"[{'version': 'v1', 'created': 'Sun, 20 May 200...",2008-11-26,"[[Abramo, L. Raul, ], [Peter, Patrick, ]]"
11607,706.2921,Peter Richardson,"Martyn Gigg and Peter Richardson (IPPP, Durham...",Herwig++,Talk given at 42nd Rencontres de Moriond on QC...,None,None,None,hep-ph,None,We describe the recent development of the He...,"[{'version': 'v1', 'created': 'Wed, 20 Jun 200...",2007-06-21,"[[Gigg, Martyn, , IPPP, Durham University], [R..."
12165,706.3479,David Love,David Love,Hypocomputation,34 pages,None,None,None,cs.OH,None,"Hypercomputational formal theories will, cle...","[{'version': 'v1', 'created': 'Sat, 23 Jun 200...",2011-11-10,"[[Love, David, ]]"
18146,708.0295,Alyson Wilson,"Sallie Keller-McNulty, Alyson Wilson, Christin...",Reliability,Published at http://dx.doi.org/10.1214/0883423...,"Statistical Science 2006, Vol. 21, No. 4, 427-427",10.1214/088342306000000664,IMS-STS-STS214INTRO,stat.ME,None,This special volume of Statistical Sciences ...,"[{'version': 'v1', 'created': 'Thu, 2 Aug 2007...",2009-09-29,"[[Keller-McNulty, Sallie, ], [Wilson, Alyson, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234762,1012.5394,Ryuichiro Kitano,"Hiraku Fukushima, Ryuichiro Kitano, Masahiro Y...",SuperTopcolor,20 pages,"JHEP 1101:111,2011",10.1007/JHEP01(2011)111,TU-876,hep-ph hep-th,http://arxiv.org/licenses/nonexclusive-distrib...,We consider a supersymmetric QCD with soft s...,"[{'version': 'v1', 'created': 'Fri, 24 Dec 201...",2011-01-28,"[[Fukushima, Hiraku, ], [Kitano, Ryuichiro, ],..."
235219,1012.5851,H. C. Spruit,"F. Zaussinger, H.C. Spruit",Semiconvection,Corrects an error in previous version: mixing ...,None,None,None,astro-ph.SR physics.flu-dyn,http://arxiv.org/licenses/nonexclusive-distrib...,A grid of numerical simulations of double-di...,"[{'version': 'v1', 'created': 'Tue, 28 Dec 201...",2015-03-17,"[[Zaussinger, F., ], [Spruit, H. C., ]]"
236707,1101.1294,Veronica Sanz,"Thomas Gregoire, Emanuel Katz, Veronica Sanz",Toptet,Modifications on the manuscript,None,10.1103/PhysRevD.85.055024,None,hep-ph hep-ex,http://arxiv.org/licenses/nonexclusive-distrib...,Final states with four tops appear in variou...,"[{'version': 'v1', 'created': 'Thu, 6 Jan 2011...",2015-03-17,"[[Gregoire, Thomas, ], [Katz, Emanuel, ], [San..."
239673,1101.4260,Mahfuza Sharmin,"Nashid Shahriar, Mahfuza Sharmin, Reaz Ahmed, ...",Networking,None,None,None,None,cs.NI cs.DC,http://arxiv.org/licenses/nonexclusive-distrib...,This paper discusses an efficient approach t...,"[{'version': 'v1', 'created': 'Sat, 22 Jan 201...",2015-03-17,"[[Shahriar, Nashid, ], [Sharmin, Mahfuza, ], [..."
248407,1103.1139,Viktor Shapovalov,Viktor I. Shapovalov,Entrostat,"9 pages, 1 figure",None,None,None,physics.gen-ph,http://arxiv.org/licenses/nonexclusive-distrib...,The reasons for introducing the concept of t...,"[{'version': 'v1', 'created': 'Sun, 6 Mar 2011...",2011-03-08,"[[Shapovalov, Viktor I., ]]"

In [7]:
df.isnull().sum()

id                     0
submitter              0
authors                0
title                  0
comments           36480
journal-ref       126845
doi                98608
report-no         228332
categories             0
license            43229
abstract               0
versions               0
update_date            0
authors_parsed         0
dtype: int64

In [8]:
#drop short titles
df = df[df['title'].str.split().str.len() >= 2]

In [9]:
# Drop rows with empty authors
df[df['authors'].notnull() & (df['authors'] == '')]

Empty DataFrame
Columns: [id, submitter, authors, title, comments, journal-ref, doi, report-no, categories, license, abstract, versions, update_date, authors_parsed]
Index: []

In [10]:
df = df.drop('abstract', axis=1)

In [11]:
#drop rows where doi is empty
df = df[df['doi'].notnull()]

In [12]:
df_small = df.sample(10)

In [13]:
'''import requests
import pandas as pd
import time

# Function to get additional information from Crossref API
def get_crossref_info(doi):
    base_url = "https://api.crossref.org/works/"
    try:
        response = requests.get(base_url + doi)
        if response.status_code == 200:
            return response.json()['message']
        else:
            return {}
    except requests.RequestException:
        return {}

# Function to extract needed information from Crossref data
def extract_needed_info(crossref_data):
    # Define the fields you need from Crossref
    fields_needed = ['publisher', 'published-print', 'published-online', 'reference-count', 'type', 'bibtex']
    extracted_info = {field: crossref_data.get(field, None) for field in fields_needed}

    # Determine publication type from 'type' field
    if 'type' in crossref_data:
        publication_type = crossref_data['type']
        if publication_type == 'journal-article':
            extracted_info['publication_type'] = '@article'
        elif publication_type in ['proceedings-article', 'conference-paper']:
            extracted_info['publication_type'] = '@inproceedings'
        # Add more mappings as necessary

    return extracted_info

'''

'import requests\nimport pandas as pd\nimport time\n\n# Function to get additional information from Crossref API\ndef get_crossref_info(doi):\n    base_url = "https://api.crossref.org/works/"\n    try:\n        response = requests.get(base_url + doi)\n        if response.status_code == 200:\n            return response.json()[\'message\']\n        else:\n            return {}\n    except requests.RequestException:\n        return {}\n\n# Function to extract needed information from Crossref data\ndef extract_needed_info(crossref_data):\n    # Define the fields you need from Crossref\n    fields_needed = [\'publisher\', \'published-print\', \'published-online\', \'reference-count\', \'type\', \'bibtex\']\n    extracted_info = {field: crossref_data.get(field, None) for field in fields_needed}\n\n    # Determine publication type from \'type\' field\n    if \'type\' in crossref_data:\n        publication_type = crossref_data[\'type\']\n        if publication_type == \'journal-article\':\n            extracted_info[\'publication_type\'] = \'@article\'\n        elif publication_type in [\'proceedings-article\', \'conference-paper\']:\n            extracted_info[\'publication_type\'] = \'@inproceedings\'\n        # Add more mappings as necessary\n\n    return extracted_info\n\n'

In [14]:
'''# Ensure columns exist in DataFrame
for field in ['publisher', 'published-print', 'published-online', 'reference-count', 'type', 'subject', 'bibtex', 'publication_type']:
    if field not in df.columns:
        df[field] = None

# Batch processing
batch_size = 1000  # Adjust based on your needs
for start in range(0, len(df), batch_size):
    end = start + batch_size
    batch = df.iloc[start:end]

    for index, row in batch.iterrows():
        crossref_data = get_crossref_info(row['doi'])
        additional_info = extract_needed_info(crossref_data)
        for key, value in additional_info.items():
            df.at[index, key] = value

        # Delay to avoid hitting rate limit
        time.sleep(0.2)'''

"# Ensure columns exist in DataFrame\nfor field in ['publisher', 'published-print', 'published-online', 'reference-count', 'type', 'subject', 'bibtex', 'publication_type']:\n    if field not in df.columns:\n        df[field] = None\n\n# Batch processing\nbatch_size = 1000  # Adjust based on your needs\nfor start in range(0, len(df), batch_size):\n    end = start + batch_size\n    batch = df.iloc[start:end]\n\n    for index, row in batch.iterrows():\n        crossref_data = get_crossref_info(row['doi'])\n        additional_info = extract_needed_info(crossref_data)\n        for key, value in additional_info.items():\n            df.at[index, key] = value\n\n        # Delay to avoid hitting rate limit\n        time.sleep(0.2)"

In [26]:
import aiohttp
import asyncio
import pandas as pd
import json
import os
import nest_asyncio

# Apply the necessary patch for asyncio in Jupyter
nest_asyncio.apply()

# Function to make asynchronous API calls
async def fetch(session, url):
    try:
        async with session.get(url) as response:
            if response.status == 200:
                return await response.text()
            else:
                return None
    except Exception as e:
        print(f"Error fetching URL {url}: {e}")
        return None

# Asynchronous batch processing function
async def fetch_all(dois):
    async with aiohttp.ClientSession() as session:
        tasks = []
        for doi in dois:
            url = f"https://api.crossref.org/works/{doi}"
            tasks.append(fetch(session, url))
        responses = await asyncio.gather(*tasks)
        return responses

# Function to extract needed information from Crossref data
def extract_needed_info(crossref_data):
    fields_needed = ['publisher', 'published-print', 'published-online', 'reference-count', 'type', 'bibtex', 'subject']
    extracted_info = {field: crossref_data.get(field, None) for field in fields_needed}

    # Determine publication type from 'type' field
    if 'type' in crossref_data:
        publication_type = crossref_data['type']
        if publication_type == 'journal-article':
            extracted_info['publication_type'] = '@article'
        elif publication_type in ['proceedings-article', 'conference-paper']:
            extracted_info['publication_type'] = '@inproceedings'

    # Extracting field of study (subject area)
    if 'subject' in crossref_data:
        subjects = crossref_data['subject']
        extracted_info['field_of_study'] = subjects

    return extracted_info

In [27]:
import warnings
warnings.filterwarnings('ignore')

In [28]:
# Check for additional fields and add them if not present
additional_fields = ['publisher', 'published-print', 'published-online', 'reference-count', 'type', 'bibtex', 'subject', 'publication_type']
for field in additional_fields:
    if field not in df.columns:
        df[field] = None

# Load checkpoint
checkpoint_file = 'checkpoint.txt'
start_index = 0
if os.path.exists(checkpoint_file):
    with open(checkpoint_file, 'r') as file:
        start_index = int(file.read().strip())

# Batch processing with async
batch_size = 100  # Adjust based on your needs
for start in range(start_index, len(df), batch_size):
    end = min(start + batch_size, len(df))
    batch_dois = df['doi'][start:end].tolist()

    # Fetch data asynchronously using the existing event loop
    responses = await fetch_all(batch_dois)  # Note the use of 'await' directly

    # Process responses and update DataFrame
    for i, response in enumerate(responses):
        if response:
            data = json.loads(response)
            crossref_data = data.get('message', {})
            additional_info = extract_needed_info(crossref_data)
            for key, value in additional_info.items():
                df.at[start + i, key] = value

    # Save checkpoint
    with open(checkpoint_file, 'w') as file:
        file.write(str(end))

    # Save DataFrame periodically
    df.to_csv('updated_data.csv', index=False)

## You can start here

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('updated_data.csv')

/var/folders/jk/l00p5drx06x4xyl4hrrg59mh0000gn/T/ipykernel_1260/686861767.py:1: DtypeWarning: Columns (13,14,15,17,19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('updated_data.csv')

In [6]:
df1 = df.sample(500)

In [8]:
df['publication_type'].value_counts()

@article          90
@inproceedings     5
Name: publication_type, dtype: int64

In [12]:
import pandas as pd
import requests

def get_crossref_author_info(doi):
    """
    Query Crossref API to get author information based on DOI.
    """
    url = f"https://api.crossref.org/works/{doi}"
    try:
        response = requests.get(url)
        if response.status_code == 200:
            authors = response.json()['message'].get('author', [])
            author_names = [f"{author.get('given', '')} {author.get('family', '')}".strip() for author in authors]
            return ', '.join(author_names)
        else:
            return None
    except requests.RequestException:
        return None

def get_crossref_publication_info(doi):
    """
    Query Crossref API to get other publication information based on DOI.
    """
    url = f"https://api.crossref.org/works/{doi}"
    try:
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()['message']
            titles = data.get('title', [])
            if titles:  # Check if titles list is not empty
                publication_title = titles[0]
            else:
                publication_title = None
            return publication_title
        else:
            return None
    except requests.RequestException:
        return None

In [13]:
# Iterate over DataFrame rows
for index, row in df1.iterrows():
    if pd.notna(row['doi']):
        author_info = get_crossref_author_info(row['doi'])
        publication_info = get_crossref_publication_info(row['doi'])

        # Update DataFrame with the author and publication information
        df1.at[index, 'refined_authors'] = author_info
        df1.at[index, 'refined_publication_title'] = publication_info

In [14]:
df1

,id,submitter,authors,title,comments,journal-ref,doi,report-no,categories,license,...,published-print,published-online,reference-count,type,bibtex,subject,publication_type,field_of_study,refined_authors,refined_publication_title
21281,711.1971,Justin David R,Justin R. David,On the dyon partition function in N=2 theories,48 pages,"JHEP0802:025,2008",10.1088/1126-6708/2008/02/025,NaN,hep-th,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Justin R David,On the dyon partition function in 𝒩 = 2 theories
102616,1001.3382,Eiji Konishi,Eiji Konishi,Modeling M-Theory Vacua via Gauged S-Duality,"31 pages, version reflecting the erratum. arXi...","Int.J.Mod.Phys.A26:4785-4816,2011;\n Int.J.Mo...",10.1142/S0217751X11054693,NaN,hep-th,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EIJI KONISHI,MODELING M-THEORY VACUA VIA GAUGED S-DUALITY
121054,1007.0229,Marcelo Kuperman,M. N. Kuperman,A model for the emergence of geopolitical divi...,NaN,"Phil. Trans. R. Soc. A 2010 368, 5695-5706",10.1098/rsta.2010.0263,NaN,nlin.AO,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M. N. Kuperman,A model for the emergence of geopolitical divi...
23046,711.4945,Hrachya Nersisyan,"H.B. Nersisyan, D.A. Osipyan and G. Zwicknagel",Renormalized cluster expansion of the microfie...,"17 pages, 10 figures, submitted to Physical Re...",NaN,10.1103/PhysRevE.77.056409,NaN,physics.plasm-ph,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"H. B. Nersisyan, D. A. Osipyan, G. Zwicknagel",Renormalized cluster expansion of the microfie...
69809,903.2896,Myung Joon Han,Myung Joon Han and Sergey Y. Savrasov,"Doping Driven ($\pi, 0$) Nesting and Magnetic ...",Table updated and discussion included,"Phys. Rev. Lett. 103, 067001 (2009)",10.1103/PhysRevLett.103.067001,NaN,cond-mat.supr-con cond-mat.mtrl-sci,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Myung Joon Han, Sergey Y. Savrasov","Doping Driven (<mml:math xmlns:mml=""http://www..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77628,906.0365,Knud Jahnke,"Knud Jahnke, David Elbaz, Eric Pantin, Asmus B...",The QSO HE0450-2958: Scantily dressed or heavi...,"12 pages, 6 figures, accepted for publication ...","Astrophys.J.700:1820-1830,2009",10.1088/0004-637X/700/2/1820,NaN,astro-ph.CO,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Knud Jahnke, David Elbaz, Eric Pantin, Asmus B...",THE QSO HE 0450-2958: SCANTILY DRESSED OR HEAV...
98248,912.1400,Xin-Jian Xu,"Xin-Jian Xu, Ming-Chen Zhou",Rank-dependent deactivation in network evolution,"5 pages, 5 figures, RevTex4","PHYSICAL REVIEW E 80, 066105 (2009)",10.1103/PhysRevE.80.066105,NaN,physics.soc-ph,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Xin-Jian Xu, Ming-Chen Zhou",Rank-dependent deactivation in network evolution
67583,902.4155,Pavel Str\'ansk\'y,"Pavel Stransky, Petr Hruska, Pavel Cejnar",Quantum chaos in the nuclear collective model:...,"12 pages, 8 figures","Physical Review E 79, 066201 (2009)",10.1103/PhysRevE.79.066201,NaN,quant-ph nlin.CD,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Pavel Stránský, Petr Hruška, Pavel Cejnar",Quantum chaos in the nuclear collective model....
135307,1011.0223,EPTCS,"\'Etienne Andr\'e (LSV, CNRS, ENSC, France)",IMITATOR II: A Tool for Solving the Good Param...,"In Proceedings INFINITY 2010, arXiv:1010.6112","EPTCS 39, 2010, pp. 91-99",10.4204/EPTCS.39.7,NaN,cs.FL cs.LO,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Étienne André,IMITATOR II: A Tool for Solving the Good Param...
29392,802.1069,Eli Rykoff,"E. S. Rykoff (UCSB), A. E. Evrard, T. A. McKay...",The L_X--M relation of Clusters of Galaxies,"5 pages, 1 figure, MNRAS accepted",NaN,10.1111/j.1745-3933.2008.00476.x,NaN,astro-ph,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"E. S. Rykoff, A. E. Evrard, T. A. McKay, M. R....",The L<sub>X</sub>–M relation of clusters of ga...

In [15]:
df1.shape

(500, 24)

In [16]:
df1.columns

Index(['id', 'submitter', 'authors', 'title', 'comments', 'journal-ref', 'doi',
       'report-no', 'categories', 'license', 'versions', 'update_date',
       'authors_parsed', 'publisher', 'published-print', 'published-online',
       'reference-count', 'type', 'bibtex', 'subject', 'publication_type',
       'field_of_study', 'refined_authors', 'refined_publication_title'],
      dtype='object')

In [17]:
df1.head()

,id,submitter,authors,title,comments,journal-ref,doi,report-no,categories,license,...,published-print,published-online,reference-count,type,bibtex,subject,publication_type,field_of_study,refined_authors,refined_publication_title
21281,711.1971,Justin David R,Justin R. David,On the dyon partition function in N=2 theories,48 pages,"JHEP0802:025,2008",10.1088/1126-6708/2008/02/025,NaN,hep-th,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Justin R David,On the dyon partition function in 𝒩 = 2 theories
102616,1001.3382,Eiji Konishi,Eiji Konishi,Modeling M-Theory Vacua via Gauged S-Duality,"31 pages, version reflecting the erratum. arXi...","Int.J.Mod.Phys.A26:4785-4816,2011;\n Int.J.Mo...",10.1142/S0217751X11054693,NaN,hep-th,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EIJI KONISHI,MODELING M-THEORY VACUA VIA GAUGED S-DUALITY
121054,1007.0229,Marcelo Kuperman,M. N. Kuperman,A model for the emergence of geopolitical divi...,NaN,"Phil. Trans. R. Soc. A 2010 368, 5695-5706",10.1098/rsta.2010.0263,NaN,nlin.AO,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M. N. Kuperman,A model for the emergence of geopolitical divi...
23046,711.4945,Hrachya Nersisyan,"H.B. Nersisyan, D.A. Osipyan and G. Zwicknagel",Renormalized cluster expansion of the microfie...,"17 pages, 10 figures, submitted to Physical Re...",NaN,10.1103/PhysRevE.77.056409,NaN,physics.plasm-ph,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"H. B. Nersisyan, D. A. Osipyan, G. Zwicknagel",Renormalized cluster expansion of the microfie...
69809,903.2896,Myung Joon Han,Myung Joon Han and Sergey Y. Savrasov,"Doping Driven ($\pi, 0$) Nesting and Magnetic ...",Table updated and discussion included,"Phys. Rev. Lett. 103, 067001 (2009)",10.1103/PhysRevLett.103.067001,NaN,cond-mat.supr-con cond-mat.mtrl-sci,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Myung Joon Han, Sergey Y. Savrasov","Doping Driven (<mml:math xmlns:mml=""http://www..."

In [18]:
df1.iloc[1]

id                                                                   1001.3382
submitter                                                         Eiji Konishi
authors                                                           Eiji Konishi
title                             Modeling M-Theory Vacua via Gauged S-Duality
comments                     31 pages, version reflecting the erratum. arXi...
journal-ref                  Int.J.Mod.Phys.A26:4785-4816,2011;\n  Int.J.Mo...
doi                                                  10.1142/S0217751X11054693
report-no                                                                  NaN
categories                                                              hep-th
license                      http://arxiv.org/licenses/nonexclusive-distrib...
versions                     [{'version': 'v1', 'created': 'Tue, 19 Jan 201...
update_date                                                         2015-05-18
authors_parsed                                       [['Konishi', 'Eiji', '']]
publisher                                                                  NaN
published-print                                                            NaN
published-online                                                           NaN
reference-count                                                            NaN
type                                                                       NaN
bibtex                                                                     NaN
subject                                                                    NaN
publication_type                                                           NaN
field_of_study                                                             NaN
refined_authors                                                   EIJI KONISHI
refined_publication_title         MODELING M-THEORY VACUA VIA GAUGED S-DUALITY
Name: 102616, dtype: object

In [19]:
import pandas as pd
import requests
import xml.etree.ElementTree as ET

def query_dblp_for_venue(title):
    url = f"https://dblp.org/search/publ/api?q={requests.utils.quote(title)}&format=xml"
    try:
        response = requests.get(url)
        if response.status_code == 200:
            root = ET.fromstring(response.content)
            hits = root.findall(".//hit")
            if hits:
                # Example: Just using the first hit, but you might want to refine this
                first_hit = hits[0]
                info = first_hit.find('.//info')
                venue = info.find('venue').text if info is not None and info.find('venue') is not None else 'Unknown'
                return venue
            else:
                return 'Unknown'
        else:
            return 'Unknown'
    except requests.RequestException:
        return 'Unknown'

In [20]:
# Iterate over DataFrame rows
for index, row in df1.iterrows():
    if pd.notna(row['title']):
        venue_info = query_dblp_for_venue(row['title'])
        df1.at[index, 'resolved_venue'] = venue_info

In [21]:
df1['resolved_venue'].value_counts()

Unknown                  496
Symmetry                   1
LSCS                       1
Comput. Phys. Commun.      1
Theory Comput.             1
Name: resolved_venue, dtype: int64

In [22]:
def query_dblp_for_venue(title):
    """
    Query the DBLP API to resolve venue names using the title of the publication.
    """
    url = f"https://dblp.org/search/publ/api?q={requests.utils.quote(title)}&format=xml"
    try:
        response = requests.get(url)
        if response.status_code == 200:
            root = ET.fromstring(response.content)
            hits = root.findall(".//hit")
            if hits:
                first_hit = hits[0]
                info = first_hit.find('.//info')
                venue = info.find('venue').text if info is not None and info.find('venue') is not None else 'Unknown'
                return venue
            else:
                return 'Unknown'
        else:
            return 'Unknown'
    except requests.RequestException:
        return 'Unknown'

In [23]:
from scholarly import scholarly, ProxyGenerator
def query_scholarly_for_venue(title):
    try:
        search_query = scholarly.search_pubs(title)
        publication = next(search_query)
        return publication['bib']['venue'] if 'venue' in publication['bib'] else 'Unknown'
    except Exception:
        return 'Unknown'

In [24]:
# pg = ProxyGenerator()
# pg.FreeProxies()
# scholarly.use_proxy(pg)

In [25]:
# Iterate over DataFrame rows
for index, row in df1.iterrows():
    # Use scholarly for fetching venue information
    venue_info = query_scholarly_for_venue(row['title'])
    df1.at[index, 'refined_venue'] = venue_info
    print('done')

done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done

In [26]:
df1.refined_venue.value_counts()

Unknown    500
Name: refined_venue, dtype: int64

In [27]:
df1

,id,submitter,authors,title,comments,journal-ref,doi,report-no,categories,license,...,reference-count,type,bibtex,subject,publication_type,field_of_study,refined_authors,refined_publication_title,resolved_venue,refined_venue
21281,711.1971,Justin David R,Justin R. David,On the dyon partition function in N=2 theories,48 pages,"JHEP0802:025,2008",10.1088/1126-6708/2008/02/025,NaN,hep-th,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Justin R David,On the dyon partition function in 𝒩 = 2 theories,Unknown,Unknown
102616,1001.3382,Eiji Konishi,Eiji Konishi,Modeling M-Theory Vacua via Gauged S-Duality,"31 pages, version reflecting the erratum. arXi...","Int.J.Mod.Phys.A26:4785-4816,2011;\n Int.J.Mo...",10.1142/S0217751X11054693,NaN,hep-th,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,EIJI KONISHI,MODELING M-THEORY VACUA VIA GAUGED S-DUALITY,Unknown,Unknown
121054,1007.0229,Marcelo Kuperman,M. N. Kuperman,A model for the emergence of geopolitical divi...,NaN,"Phil. Trans. R. Soc. A 2010 368, 5695-5706",10.1098/rsta.2010.0263,NaN,nlin.AO,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,M. N. Kuperman,A model for the emergence of geopolitical divi...,Unknown,Unknown
23046,711.4945,Hrachya Nersisyan,"H.B. Nersisyan, D.A. Osipyan and G. Zwicknagel",Renormalized cluster expansion of the microfie...,"17 pages, 10 figures, submitted to Physical Re...",NaN,10.1103/PhysRevE.77.056409,NaN,physics.plasm-ph,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"H. B. Nersisyan, D. A. Osipyan, G. Zwicknagel",Renormalized cluster expansion of the microfie...,Unknown,Unknown
69809,903.2896,Myung Joon Han,Myung Joon Han and Sergey Y. Savrasov,"Doping Driven ($\pi, 0$) Nesting and Magnetic ...",Table updated and discussion included,"Phys. Rev. Lett. 103, 067001 (2009)",10.1103/PhysRevLett.103.067001,NaN,cond-mat.supr-con cond-mat.mtrl-sci,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,"Myung Joon Han, Sergey Y. Savrasov","Doping Driven (<mml:math xmlns:mml=""http://www...",Unknown,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77628,906.0365,Knud Jahnke,"Knud Jahnke, David Elbaz, Eric Pantin, Asmus B...",The QSO HE0450-2958: Scantily dressed or heavi...,"12 pages, 6 figures, accepted for publication ...","Astrophys.J.700:1820-1830,2009",10.1088/0004-637X/700/2/1820,NaN,astro-ph.CO,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,"Knud Jahnke, David Elbaz, Eric Pantin, Asmus B...",THE QSO HE 0450-2958: SCANTILY DRESSED OR HEAV...,Unknown,Unknown
98248,912.1400,Xin-Jian Xu,"Xin-Jian Xu, Ming-Chen Zhou",Rank-dependent deactivation in network evolution,"5 pages, 5 figures, RevTex4","PHYSICAL REVIEW E 80, 066105 (2009)",10.1103/PhysRevE.80.066105,NaN,physics.soc-ph,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,"Xin-Jian Xu, Ming-Chen Zhou",Rank-dependent deactivation in network evolution,Unknown,Unknown
67583,902.4155,Pavel Str\'ansk\'y,"Pavel Stransky, Petr Hruska, Pavel Cejnar",Quantum chaos in the nuclear collective model:...,"12 pages, 8 figures","Physical Review E 79, 066201 (2009)",10.1103/PhysRevE.79.066201,NaN,quant-ph nlin.CD,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,"Pavel Stránský, Petr Hruška, Pavel Cejnar",Quantum chaos in the nuclear collective model....,Unknown,Unknown
135307,1011.0223,EPTCS,"\'Etienne Andr\'e (LSV, CNRS, ENSC, France)",IMITATOR II: A Tool for Solving the Good Param...,"In Proceedings INFINITY 2010, arXiv:1010.6112","EPTCS 39, 2010, pp. 91-99",10.4204/EPTCS.39.7,NaN,cs.FL cs.LO,http://arxiv.org/licenses/nonexclusive-distrib...,...,NaN,NaN,NaN,NaN,NaN,NaN,Étienne André,IMITATOR II: A Tool for Solving the Good Param...,Unknown,Unknown
29392,802.1069,Eli Rykoff,"E. S. Rykoff (UCSB), A. E. Evrard, T. A. McKay...",The L_X--M relation of Clusters of Galaxies,"5 pages, 1 figure, MNRAS accepted",NaN,10.1111/j.1745-3933.2008.00476.x,NaN,astro-ph,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"E. S. Rykoff, A. E. Evrard, T. A. McKay, M. R....",The L<sub>X</sub>–M relation of clusters of ga...,Unknown,Unknown

In [28]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500 entries, 21281 to 29392
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         500 non-null    float64
 1   submitter                  500 non-null    object
 2   authors                    500 non-null    object
 3   title                      500 non-null    object
 4   comments                   460 non-null    object
 5   journal-ref                348 non-null    object
 6   doi                        500 non-null    object
 7   report-no                  55 non-null     object
 8   categories                 500 non-null    object
 9   license                    402 non-null    object
 10  versions                   500 non-null    object
 11  update_date                500 non-null    object
 12  authors_parsed             500 non-null    object
 13  publisher                  1 non-null      object
 14  published-print            1 non-null      object
 15  published-online           0 non-null      object
 16  reference-count            1 non-null      float64
 17  type                       1 non-null      object
 18  bibtex                     0 non-null      float64
 19  subject                    0 non-null      object
 20  publication_type           1 non-null      object
 21  field_of_study             0 non-null      object
 22  refined_authors            496 non-null    object
 23  refined_publication_title  495 non-null    object
 24  resolved_venue             500 non-null    object
 25  refined_venue              500 non-null    object
dtypes: float64(3), object(23)
memory usage: 121.6+ KB

In [31]:
import pandas as pd
import requests


# Define a function to infer gender for a given name using the Genderize.io API
def infer_gender(name):
    url = f"https://api.genderize.io?name={name}"
    
    response = requests.get(url)
    if response.status_code == 200:
        result = response.json()
        return result.get("gender", "unknown")
    else:
        return "unknown"

def process_authors(authors):
    # Handle None values
    if authors is None:
        return 'unknown'

    # Split the author string by comma to get individual names
    author_list = authors.split(", ")
    gendered_authors = []

    for author in author_list:
        # Check if the author's name is not empty and contains a space
        if author and " " in author:
            # Extract first name (assuming first word is the first name)
            first_name = author.split()[0]
            # Infer gender for the first name
            gender = infer_gender(first_name)
        else:
            # Default to 'unknown' if the author's name is not in the expected format
            gender = "unknown"

        # Append the author name with gender
        gendered_authors.append(f"{author} ({gender})")

    return ", ".join(gendered_authors)

In [32]:
# Apply the function to the 'refined_authors' column
df1['authors_with_gender'] = df1['refined_authors'].apply(process_authors)

In [33]:
df1.iloc[1]

id                                                                   1001.3382
submitter                                                         Eiji Konishi
authors                                                           Eiji Konishi
title                             Modeling M-Theory Vacua via Gauged S-Duality
comments                     31 pages, version reflecting the erratum. arXi...
journal-ref                  Int.J.Mod.Phys.A26:4785-4816,2011;\n  Int.J.Mo...
doi                                                  10.1142/S0217751X11054693
report-no                                                                  NaN
categories                                                              hep-th
license                      http://arxiv.org/licenses/nonexclusive-distrib...
versions                     [{'version': 'v1', 'created': 'Tue, 19 Jan 201...
update_date                                                         2015-05-18
authors_parsed                                       [['Konishi', 'Eiji', '']]
publisher                                                                  NaN
published-print                                                            NaN
published-online                                                           NaN
reference-count                                                            NaN
type                                                                       NaN
bibtex                                                                     NaN
subject                                                                    NaN
publication_type                                                           NaN
field_of_study                                                             NaN
refined_authors                                                   EIJI KONISHI
refined_publication_title         MODELING M-THEORY VACUA VIA GAUGED S-DUALITY
resolved_venue                                                         Unknown
refined_venue                                                          Unknown
authors_with_gender                                        EIJI KONISHI (male)
Name: 102616, dtype: object

In [34]:
df1.categories.unique()

array(['hep-th', 'nlin.AO', 'physics.plasm-ph',
       'cond-mat.supr-con cond-mat.mtrl-sci', 'cond-mat.mtrl-sci',
       'cond-mat.mes-hall', 'quant-ph',
       'cond-mat.soft cond-mat.mtrl-sci nlin.PS', 'cond-mat.str-el',
       'astro-ph.CO', 'quant-ph cond-mat.quant-gas nlin.PS',
       'quant-ph cond-mat.str-el', 'hep-ph',
       'hep-th cond-mat.quant-gas cond-mat.str-el hep-ph nucl-th',
       'math.GR math.AG math.DS', 'math.DG', 'math.CA math.CO',
       'astro-ph', 'astro-ph.HE astro-ph.SR', 'nucl-ex',
       'hep-ph astro-ph.CO', 'gr-qc astro-ph hep-th quant-ph', 'nucl-th',
       'cs.AI', 'astro-ph.SR', 'cond-mat.supr-con cond-mat.stat-mech',
       'gr-qc', 'cond-mat.mes-hall cond-mat.str-el',
       'math.DS math-ph math.DG math.GT math.MP', 'hep-lat',
       'astro-ph.HE', 'cond-mat.supr-con',
       'cond-mat.dis-nn cond-mat.mtrl-sci',
       'physics.atom-ph hep-ph nucl-th', 'astro-ph.CO hep-ph hep-th',
       'hep-ph hep-ex', 'nucl-th hep-ph', 'quant-ph physics.atom-ph',
       'cond-mat.stat-mech math-ph math.MP', 'math.AT math.NT',
       'math-ph math.MP', 'astro-ph.SR astro-ph.HE',
       'math-ph hep-ph math.MP', 'cond-mat.dis-nn', 'gr-qc hep-th',
       'cond-mat.mes-hall cond-mat.mtrl-sci', 'math.DS',
       'hep-ph hep-th nucl-th', 'physics.flu-dyn physics.plasm-ph',
       'hep-th math.QA', 'nucl-th hep-ph nucl-ex', 'math.KT math.RT',
       'quant-ph cs.GT', 'cond-mat.dis-nn cond-mat.stat-mech',
       'hep-th math-ph math.MP', 'astro-ph nucl-th',
       'cond-mat.mtrl-sci cond-mat.mes-hall',
       'math-ph math.MP physics.atm-clus physics.flu-dyn physics.plasm-ph',
       'nlin.CD', 'cond-mat.soft', 'cond-mat.soft cond-mat.mtrl-sci',
       'cond-mat.str-el cond-mat.mtrl-sci',
       'cond-mat.stat-mech cond-mat.str-el quant-ph', 'astro-ph.GA',
       'physics.atom-ph', 'cond-mat.soft physics.class-ph',
       'cond-mat.str-el cond-mat.mes-hall', 'astro-ph.IM',
       'cond-mat.supr-con cond-mat.other', 'q-bio.BM physics.chem-ph',
       'physics.acc-ph hep-ex',
       'cond-mat.str-el cond-mat.other physics.chem-ph',
       'astro-ph.SR astro-ph.GA', 'nucl-ex hep-ex hep-ph nucl-th',
       'hep-th hep-ph', 'cond-mat.mtrl-sci cond-mat.stat-mech',
       'math.AG math.CV', 'math.QA math-ph math.MP',
       'math.CO cs.DM math.OC', 'cond-mat.mes-hall nlin.CD',
       'hep-th astro-ph gr-qc', 'astro-ph hep-ph', 'cond-mat.quant-gas',
       'astro-ph gr-qc', 'math-ph math.MP quant-ph',
       'nlin.CD cond-mat.stat-mech', 'astro-ph.SR astro-ph.IM',
       'physics.acc-ph', 'math-ph math.AP math.MP',
       'astro-ph.CO astro-ph.EP', 'math.GT math.AG', 'hep-ex',
       'hep-th math-ph math.MP quant-ph', 'astro-ph.EP',
       'cond-mat.stat-mech', 'cond-mat.soft cond-mat.stat-mech',
       'astro-ph.CO gr-qc hep-th', 'math.OC', 'hep-th hep-ph nucl-th',
       'physics.class-ph physics.pop-ph',
       'hep-th math-ph math.MP physics.class-ph',
       'astro-ph.CO gr-qc hep-ph hep-th',
       'cond-mat.mes-hall cond-mat.other', 'astro-ph.EP astro-ph.SR',
       'cond-mat.mes-hall quant-ph', 'math.LO', 'cs.NI',
       'cond-mat.supr-con cond-mat.str-el', 'q-fin.ST cond-mat.stat-mech',
       'cond-mat.mtrl-sci cond-mat.dis-nn cond-mat.mes-hall cond-mat.other cond-mat.soft cond-mat.stat-mech',
       'hep-ph astro-ph.CO hep-ex',
       'physics.flu-dyn physics.comp-ph physics.geo-ph physics.space-ph',
       'cs.DS cs.CC cs.GT', 'physics.optics', 'math.GT',
       'astro-ph gr-qc physics.plasm-ph', 'astro-ph.EP physics.geo-ph',
       'cond-mat.quant-gas cond-mat.str-el',
       'astro-ph.CO astro-ph.GA hep-th', 'gr-qc hep-th math-ph math.MP',
       'math.CO', 'cond-mat.dis-nn physics.soc-ph',
       'math.KT math.AT math.DS math.OA', 'cond-mat.stat-mech quant-ph',
       'math.GN', 'hep-ex astro-ph hep-ph',
       'astro-ph.GA astro-ph.CO astro-ph.HE hep-ph nucl-th',
       'q-bio.SC cond-mat.soft q-bio.BM', 'astro-ph.CO hep-ex nucl-ex',
       'physics.space-ph', 'math.AC', 'math.FA', 'hep-ph physics.atom-ph',
       'physics.geo-ph', 'math.PR', 'physics.soc-ph q-bio.OT',
       'math-ph math.AP math.MP physics.optics',
       'astro-ph.CO astro-ph.GA', 'q-bio.NC q-bio.QM',
       'cond-mat.mes-hall cond-mat.dis-nn nlin.CD', 'hep-ex nucl-ex',
       'gr-qc astro-ph hep-th', 'math.SG', 'math.PR math.CA',
       'quant-ph cond-mat.mes-hall',
       'cond-mat.mes-hall cond-mat.quant-gas cond-mat.str-el',
       'math.AT math.DG', 'physics.atom-ph physics.atm-clus',
       'astro-ph.CO gr-qc', 'cond-mat.soft q-bio.BM', 'cs.DM math.CO',
       'physics.class-ph physics.gen-ph physics.hist-ph',
       'cond-mat.mtrl-sci cond-mat.soft', 'physics.hist-ph',
       'hep-ph hep-lat nucl-th', 'hep-ph astro-ph hep-ex',
       'astro-ph.SR astro-ph.EP', 'astro-ph.HE hep-ph', 'math.RT math.CO',
       'math-ph cond-mat.mes-hall math.MP', 'q-bio.MN cond-mat.dis-nn',
       'math-ph hep-th math.MP', 'math.RT', 'math.SG math.GT',
       'astro-ph.SR hep-ph', 'stat.AP', 'hep-th gr-qc',
       'cond-mat.mes-hall cond-mat.dis-nn', 'cs.IT math.IT',
       'math.DS math.CV', 'stat.ME q-bio.GN', 'quant-ph math-ph math.MP',
       'math.NA', 'physics.bio-ph cond-mat.stat-mech q-bio.CB',
       'cond-mat.supr-con cond-mat.mes-hall', 'physics.ins-det',
       'stat.ME math.HO', 'stat.ML cs.LG', 'hep-ph hep-th',
       'math.DG math-ph math.MP math.SG', 'math.CV',
       'astro-ph.GA physics.plasm-ph', 'math.CO math-ph math.MP',
       'hep-th hep-lat hep-ph', 'math.RT math.CT', 'nlin.SI',
       'cond-mat.mes-hall cond-mat.mtrl-sci quant-ph',
       'astro-ph gr-qc hep-th', 'hep-th astro-ph.CO gr-qc hep-ph',
       'hep-ph astro-ph.CO hep-th', 'math.RT math.FA',
       'cond-mat.mes-hall cond-mat.supr-con', 'math.OA',
       'q-bio.PE q-bio.QM', 'math.ST math.PR stat.TH',
       'astro-ph.GA astro-ph.SR', 'cond-mat.mtrl-sci cond-mat.str-el',
       'cond-mat.str-el quant-ph', 'cond-mat.stat-mech cond-mat.soft',
       'quant-ph cond-mat.other physics.atom-ph',
       'cond-mat.mtrl-sci cond-mat.other', 'math.ST stat.ME stat.TH',
       'physics.soc-ph', 'quant-ph nlin.CD', 'cs.FL cs.LO'], dtype=object)

In [35]:
def map_category_to_field_of_study(category):
    if 'astro-ph' in category:
        return "Astronomy and Astrophysics"
    elif 'hep-ph' in category or 'hep-ex' in category or 'hep-th' in category or 'hep-lat' in category:
        return "High Energy Physics"
    elif 'quant-ph' in category:
        return "Quantum Physics"
    elif 'cond-mat' in category:
        return "Condensed Matter Physics"
    elif any(math_topic in category for math_topic in ['math.', 'stat.', 'cs.']):
        return "Mathematics and Computer Science"
    elif 'nucl-' in category:
        return "Nuclear Physics"
    elif 'gr-qc' in category:
        return "General Relativity and Quantum Cosmology"
    elif 'nlin.' in category:
        return "Nonlinear Sciences"
    elif 'physics.' in category:
        return "General Physics"
    elif 'q-bio' in category:
        return "Quantitative Biology"
    elif 'cs.' in category:
        return "Computer Science"
    elif 'q-fin' in category:
        return "Quantitative Finance"
    else:
        return "Other"

In [36]:
# Apply the function to create a new column
df1['field_of_study'] = df1['categories'].apply(map_category_to_field_of_study)

In [37]:
df1.sample(2)

,id,submitter,authors,title,comments,journal-ref,doi,report-no,categories,license,...,type,bibtex,subject,publication_type,field_of_study,refined_authors,refined_publication_title,resolved_venue,refined_venue,authors_with_gender
24070,712.1638,Enrico Prati,"Enrico Prati, Marco Fanciulli, Alessandro Cald...",Time Dependent Inelastic Emission and Capture ...,8 Figures,"E. Prati et al., Effect of microwave irradiati...",10.1063/1.2924407,NaN,cond-mat.mes-hall,NaN,...,NaN,NaN,NaN,NaN,Condensed Matter Physics,"Enrico Prati, Marco Fanciulli, Alessandro Cald...",Effect of microwave irradiation on the emissio...,Unknown,Unknown,"Enrico Prati (male), Marco Fanciulli (male), A..."
8492,707.0331,Dian Yong Chen,Y. B. Dong,Target mass corrections and twist-3 in the nuc...,"11 pages, 1 figures","Phys.Lett.B653:18-22,2007",10.1016/j.physletb.2007.07.022,NaN,hep-ph,NaN,...,NaN,NaN,NaN,NaN,High Energy Physics,Y.B. Dong,Target mass corrections and twist-3 in the nuc...,Unknown,Unknown,Y.B. Dong (None)

In [38]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500 entries, 21281 to 29392
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         500 non-null    float64
 1   submitter                  500 non-null    object
 2   authors                    500 non-null    object
 3   title                      500 non-null    object
 4   comments                   460 non-null    object
 5   journal-ref                348 non-null    object
 6   doi                        500 non-null    object
 7   report-no                  55 non-null     object
 8   categories                 500 non-null    object
 9   license                    402 non-null    object
 10  versions                   500 non-null    object
 11  update_date                500 non-null    object
 12  authors_parsed             500 non-null    object
 13  publisher                  1 non-null      object
 14  published-print            1 non-null      object
 15  published-online           0 non-null      object
 16  reference-count            1 non-null      float64
 17  type                       1 non-null      object
 18  bibtex                     0 non-null      float64
 19  subject                    0 non-null      object
 20  publication_type           1 non-null      object
 21  field_of_study             500 non-null    object
 22  refined_authors            496 non-null    object
 23  refined_publication_title  495 non-null    object
 24  resolved_venue             500 non-null    object
 25  refined_venue              500 non-null    object
 26  authors_with_gender        500 non-null    object
dtypes: float64(3), object(24)
memory usage: 125.5+ KB

In [39]:
def get_crossref_publication_info_extended(doi):
    """
    Query Crossref API to get extended publication information based on DOI.
    """
    url = f"https://api.crossref.org/works/{doi}"
    try:
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()['message']

            # Extract additional information
            publication_year = data.get('published-print', data.get('published-online', {})).get('date-parts', [[None]])[0][0]
            journal_name = data.get('container-title', [None])[0]
            volume = data.get('volume', None)
            issue = data.get('issue', None)
            pages = data.get('page', None)

            return publication_year, journal_name, volume, issue, pages
        else:
            return None, None, None, None, None
    except requests.RequestException:
        return None, None, None, None, None

In [40]:
# Iterate over DataFrame rows
for index, row in df1.iterrows():
    if pd.notna(row['doi']):
        # Get extended publication info
        pub_year, journal, volume, issue, pages = get_crossref_publication_info_extended(row['doi'])

        # Update DataFrame with the new information
        df1.at[index, 'publication_year'] = pub_year
        df1.at[index, 'journal_name'] = journal
        df1.at[index, 'volume'] = volume
        df1.at[index, 'issue'] = issue
        df1.at[index, 'pages'] = pages

In [49]:
df1['publication_year'] = df1['publication_year'].astype('Int64')

In [55]:
df1.shape

(500, 32)

In [125]:
df1.to_csv('updated_data_new.csv')

## Better off starting here with 'updated_data_new.csv'

In [126]:
# remove comment below

df1 = pd.read_csv('updated_data_new.csv')
df1.drop('Unnamed: 0', axis=1, inplace=True)

In [40]:
!pip install psycopg2

Collecting psycopg2
  Downloading psycopg2-2.9.9.tar.gz (384 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 384.9/384.9 kB 488.3 kB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
Requirement already satisfied: sqlalchemy in /Users/dayvheed/opt/anaconda3/lib/python3.9/site-packages (1.4.46)
Requirement already satisfied: pandas in /Users/dayvheed/opt/anaconda3/lib/python3.9/site-packages (1.5.2)
Requirement already satisfied: greenlet!=0.4.17 in /Users/dayvheed/opt/anaconda3/lib/python3.9/site-packages (from sqlalchemy) (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/dayvheed/opt/anaconda3/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/dayvheed/opt/anaconda3/lib/python3.9/site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.20.3 in /Users/dayvheed/opt/anaconda3/lib/python3.9/site-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /Users/dayvheed/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Building wheels for collected packages: psycopg2
  Building wheel for psycopg2 (setup.py) ... done
  Created wheel for psycopg2: filename=psycopg2-2.9.9-cp39-cp39-macosx_10_9_x86_64.whl size=133954 sha256=400a7f85b9c4bdec0b10e1797db0fa5793a28fc27502f58b29bff33baa87f6af
  Stored in directory: /Users/dayvheed/Library/Caches/pip/wheels/3a/06/25/adb124afd8c8346e45c455f6586f7289cde2b4e339dfbcd9e9
Successfully built psycopg2
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.9
WARNING: There was an error checking the latest version of pip.

In [41]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /Users/dayvheed/opt/anaconda3/lib/python3.9/site-packages (1.4.46)
Requirement already satisfied: greenlet!=0.4.17 in /Users/dayvheed/opt/anaconda3/lib/python3.9/site-packages (from sqlalchemy) (2.0.1)
WARNING: There was an error checking the latest version of pip.

In [54]:
from sqlalchemy import create_engine
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# PostgreSQL connection parameters
host = "localhost"  # or your host
user = os.getenv("DB_USER")
pwd = os.getenv("DB_PASSWORD")

# Connect to a default database (like 'postgres')
default_db = "postgres"
engine = create_engine(f'postgresql://{user}:{pwd}@{host}:5434/{default_db}', echo=True)

# Database name to create
new_db_name = "dwh"

# Use a connection with autocommit mode to create the new database
with engine.connect().execution_options(isolation_level="AUTOCOMMIT") as conn:
    conn.execute(f"CREATE DATABASE {new_db_name}")
    print(f"Database '{new_db_name}' created successfully")

2023-12-10 13:44:12,734 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-12-10 13:44:12,736 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-12-10 13:44:12,737 INFO sqlalchemy.engine.Engine select current_schema()
2023-12-10 13:44:12,738 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-12-10 13:44:12,739 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-12-10 13:44:12,739 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-12-10 13:44:12,740 INFO sqlalchemy.engine.Engine CREATE DATABASE dwh
2023-12-10 13:44:12,741 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-12-10 13:44:12,832 INFO sqlalchemy.engine.Engine COMMIT using DBAPI connection.commit(), DBAPI should ignore due to autocommit mode
Database 'dwh' created successfully

In [127]:
create_tables_query = '''
-- Drop existing tables if they exist
DROP TABLE IF EXISTS publication_author_junction CASCADE;
DROP TABLE IF EXISTS fact_publications CASCADE;
DROP TABLE IF EXISTS dim_title CASCADE;
DROP TABLE IF EXISTS dim_submitter CASCADE;
DROP TABLE IF EXISTS dim_license CASCADE;
DROP TABLE IF EXISTS dim_journal_ref CASCADE;
DROP TABLE IF EXISTS dim_field_of_study CASCADE;
DROP TABLE IF EXISTS dim_authors CASCADE;

-- Create Dimension Tables
CREATE TABLE dim_submitter (
    submitter_id SERIAL PRIMARY KEY,
    submitter_name VARCHAR(255)
);

CREATE TABLE dim_authors (
    author_id SERIAL PRIMARY KEY,
    author_name VARCHAR(255),
    gender VARCHAR(50)
);

CREATE TABLE dim_title (
    title_id SERIAL PRIMARY KEY,
    title TEXT,
    refined_publication_title TEXT
);

CREATE TABLE dim_journal_ref (
    journal_ref_id SERIAL PRIMARY KEY,
    journal_ref VARCHAR(255),
    resolved_venue VARCHAR(255),
    refined_venue VARCHAR(255)
);

CREATE TABLE dim_license (
    license_id SERIAL PRIMARY KEY,
    license_type VARCHAR(255)
);

CREATE TABLE dim_field_of_study (
    field_of_study_id SERIAL PRIMARY KEY,
    field_name VARCHAR(255)
);

-- Create Fact Table
CREATE TABLE fact_publications (
    publication_id VARCHAR(255) PRIMARY KEY,
    submitter_id INT REFERENCES dim_submitter(submitter_id),
    title_id INT REFERENCES dim_title(title_id),
    doi VARCHAR(255),
    report_no VARCHAR(255),
    comments TEXT,
    publication_type VARCHAR(255),
    journal_ref_id INT REFERENCES dim_journal_ref(journal_ref_id),
    license_id INT REFERENCES dim_license(license_id),
    field_of_study_id INT REFERENCES dim_field_of_study(field_of_study_id),
    publication_year INT,  -- New column for publication year
    journal_name VARCHAR(255),  -- New column for journal name
    volume VARCHAR(50),  -- New column for volume
    issue VARCHAR(50),  -- New column for issue
    pages VARCHAR(100)  -- New column for pages
);

-- Create Junction Table for Many-to-Many Relationship between Publications and Authors
CREATE TABLE publication_author_junction (
    publication_id VARCHAR(255),
    author_id INT,
    PRIMARY KEY (publication_id, author_id),
    FOREIGN KEY (publication_id) REFERENCES fact_publications(publication_id),
    FOREIGN KEY (author_id) REFERENCES dim_authors(author_id)
);

'''

In [128]:
from sqlalchemy import create_engine, text
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# PostgreSQL connection parameters
host = "localhost"
port = "5434"
user = os.getenv("DB_USER")
pwd = os.getenv("DB_PASSWORD")
db = "dwh"

engine = create_engine(f'postgresql://{user}:{pwd}@{host}:{port}/dwh', echo=True)

try:
    with engine.connect() as conn:
        conn.execute(text(create_tables_query))
        conn.execute(text("COMMIT;"))  # Explicit commit
        print("Tables created successfully")
except Exception as e:
    print(f"An error occurred: {e}")

2023-12-10 14:49:57,619 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-12-10 14:49:57,620 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-12-10 14:49:57,623 INFO sqlalchemy.engine.Engine select current_schema()
2023-12-10 14:49:57,623 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-12-10 14:49:57,625 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-12-10 14:49:57,626 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-12-10 14:49:57,629 INFO sqlalchemy.engine.Engine
-- Drop existing tables if they exist
DROP TABLE IF EXISTS publication_author_junction CASCADE;
DROP TABLE IF EXISTS fact_publications CASCADE;
DROP TABLE IF EXISTS dim_title CASCADE;
DROP TABLE IF EXISTS dim_submitter CASCADE;
DROP TABLE IF EXISTS dim_license CASCADE;
DROP TABLE IF EXISTS dim_journal_ref CASCADE;
DROP TABLE IF EXISTS dim_field_of_study CASCADE;
DROP TABLE IF EXISTS dim_authors CASCADE;

-- Create Dimension Tables
CREATE TABLE dim_submitter (
    submitter_id SERIAL PRIMARY KEY,
    submitter_name VARCHAR(255)
);

CREATE TABLE dim_authors (
    author_id SERIAL PRIMARY KEY,
    author_name VARCHAR(255),
    gender VARCHAR(50)
);

CREATE TABLE dim_title (
    title_id SERIAL PRIMARY KEY,
    title TEXT,
    refined_publication_title TEXT
);

CREATE TABLE dim_journal_ref (
    journal_ref_id SERIAL PRIMARY KEY,
    journal_ref VARCHAR(255),
    resolved_venue VARCHAR(255),
    refined_venue VARCHAR(255)
);

CREATE TABLE dim_license (
    license_id SERIAL PRIMARY KEY,
    license_type VARCHAR(255)
);

CREATE TABLE dim_field_of_study (
    field_of_study_id SERIAL PRIMARY KEY,
    field_name VARCHAR(255)
);

-- Create Fact Table
CREATE TABLE fact_publications (
    publication_id VARCHAR(255) PRIMARY KEY,
    submitter_id INT REFERENCES dim_submitter(submitter_id),
    title_id INT REFERENCES dim_title(title_id),
    doi VARCHAR(255),
    report_no VARCHAR(255),
    comments TEXT,
    publication_type VARCHAR(255),
    journal_ref_id INT REFERENCES dim_journal_ref(journal_ref_id),
    license_id INT REFERENCES dim_license(license_id),
    field_of_study_id INT REFERENCES dim_field_of_study(field_of_study_id),
    publication_year INT,  -- New column for publication year
    journal_name VARCHAR(255),  -- New column for journal name
    volume VARCHAR(50),  -- New column for volume
    issue VARCHAR(50),  -- New column for issue
    pages VARCHAR(100)  -- New column for pages
);

-- Create Junction Table for Many-to-Many Relationship between Publications and Authors
CREATE TABLE publication_author_junction (
    publication_id VARCHAR(255),
    author_id INT,
    PRIMARY KEY (publication_id, author_id),
    FOREIGN KEY (publication_id) REFERENCES fact_publications(publication_id),
    FOREIGN KEY (author_id) REFERENCES dim_authors(author_id)
);


2023-12-10 14:49:57,631 INFO sqlalchemy.engine.Engine [generated in 0.00196s] {}
2023-12-10 14:49:57,667 INFO sqlalchemy.engine.Engine COMMIT;
2023-12-10 14:49:57,669 INFO sqlalchemy.engine.Engine [generated in 0.00137s] {}
Tables created successfully

In [129]:
# Create a database connection
engine = create_engine(f'postgresql://{user}:{pwd}@{host}:5434/{db}')

# Query to list all tables in the database
tables_query = "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'"
tables = pd.read_sql(tables_query, engine)
print("Tables in the database:", tables['table_name'].tolist())

Tables in the database: ['dim_submitter', 'fact_publications', 'dim_title', 'dim_journal_ref', 'dim_license', 'dim_field_of_study', 'publication_author_junction', 'dim_authors']

In [130]:
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

# Load environment variables
load_dotenv()

# PostgreSQL connection parameters
host = "localhost"  # or your host
db = "dwh"
user = os.getenv("DB_USER")
pwd = os.getenv("DB_PASSWORD")

# Create a database connection
engine = create_engine(f'postgresql://{user}:{pwd}@{host}:5434/{db}', echo=False)

def get_or_create_author(author_name, gender, engine):
    if pd.isna(author_name):
        return None

    # Check if the author already exists
    select_query = "SELECT author_id FROM dim_authors WHERE author_name = %s"
    result = engine.execute(select_query, [author_name]).fetchone()
    if result:
        return result[0]

    # If not, insert the new author with gender and return the author_id
    insert_query = "INSERT INTO dim_authors (author_name, gender) VALUES (%s, %s) RETURNING author_id"
    result = engine.execute(insert_query, [author_name, gender]).fetchone()
    return result[0]

def get_or_create_primary_key(value, table_name, column_name, primary_key_column, engine):
    if pd.isna(value):
        return None

    # Check if the value already exists and return its primary key
    select_query = f"SELECT {primary_key_column} FROM {table_name} WHERE {column_name} = %s"
    result = engine.execute(select_query, [value]).fetchone()
    if result:
        return result[0]

    # If not, insert the new value and return its primary key
    insert_query = f"INSERT INTO {table_name} ({column_name}) VALUES (%s) RETURNING {primary_key_column}"
    result = engine.execute(insert_query, [value]).fetchone()
    return result[0]

def populate_tables(df, engine):
    for index, row in df.iterrows():
        submitter_id = get_or_create_primary_key(row['submitter'], 'dim_submitter', 'submitter_name', 'submitter_id', engine)
        title_id = get_or_create_primary_key(row['title'], 'dim_title', 'title', 'title_id', engine)
        journal_ref_id = get_or_create_primary_key(row['journal-ref'], 'dim_journal_ref', 'journal_ref', 'journal_ref_id', engine)
        license_id = get_or_create_primary_key(row['license'], 'dim_license', 'license_type', 'license_id', engine)
        field_of_study_id = get_or_create_primary_key(row['field_of_study'], 'dim_field_of_study', 'field_name', 'field_of_study_id', engine)

        # Extract and include new columns in fact_publications table
        fact_row = {
            'publication_id': row['doi'],
            'submitter_id': submitter_id,
            'title_id': title_id,
            'doi': row['doi'],
            'report_no': row.get('report-no', None),
            'comments': row['comments'],
            'publication_type': row.get('publication_type', None),
            'journal_ref_id': journal_ref_id,
            'license_id': license_id,
            'field_of_study_id': field_of_study_id,
            'publication_year': row.get('publication_year', None),  # Make sure column name matches exactly
            'journal_name': row.get('journal_name', None),        # Make sure column name matches exactly
            'volume': row.get('volume', None),                    # Make sure column name matches exactly
            'issue': row.get('issue', None),                      # Make sure column name matches exactly
            'pages': row.get('pages', None)                       # Make sure column name matches exactly
        }
        df_fact = pd.DataFrame([fact_row])
        df_fact.to_sql('fact_publications', engine, if_exists='append', index=False)

        # Handle authors and populate publication_author_junction
        if pd.notna(row['authors_with_gender']):
            for author_with_gender in row['authors_with_gender'].split(', '):
                parts = author_with_gender.rsplit(' (', 1)
                author_name = parts[0].strip()
                gender = parts[1].rstrip(')') if len(parts) > 1 else None

                author_id = get_or_create_author(author_name, gender, engine)

                # Check if combination of publication_id and author_id already exists
                junction_check_query = "SELECT 1 FROM publication_author_junction WHERE publication_id = %s AND author_id = %s"
                exists = engine.execute(junction_check_query, (row['doi'], author_id)).fetchone()

                if not exists:
                    # Insert into junction table if combination does not exist
                    junction_row = {'publication_id': row['doi'], 'author_id': author_id}
                    df_junction = pd.DataFrame([junction_row])
                    df_junction.to_sql('publication_author_junction', engine, if_exists='append', index=False)

# Assuming df1 is your DataFrame
populate_tables(df1, engine)

# Close the database connection
engine.dispose()

In [131]:
# Create a database connection
engine = create_engine(f'postgresql://{user}:{pwd}@{host}:5434/{db}')

# Get a glimpse of each table
for table in tables['table_name']:
    query = f'SELECT * FROM public."{table}" LIMIT 5'
    data = pd.read_sql(query, engine)
    print(f"\nTable: {table}")
    print(data)

Table: dim_submitter
   submitter_id     submitter_name
0             1     Justin David R
1             2       Eiji Konishi
2             3   Marcelo Kuperman
3             4  Hrachya Nersisyan
4             5     Myung Joon Han

Table: fact_publications
                   publication_id  submitter_id  title_id  \
0   10.1088/1126-6708/2008/02/025             1         1
1       10.1142/S0217751X11054693             2         2
2          10.1098/rsta.2010.0263             3         3
3      10.1103/PhysRevE.77.056409             4         4
4  10.1103/PhysRevLett.103.067001             5         5

                              doi report_no  \
0   10.1088/1126-6708/2008/02/025      None
1       10.1142/S0217751X11054693      None
2          10.1098/rsta.2010.0263      None
3      10.1103/PhysRevE.77.056409      None
4  10.1103/PhysRevLett.103.067001      None

                                            comments publication_type  \
0                                           48 pages             None
1  31 pages, version reflecting the erratum. arXi...             None
2                                               None             None
3  17 pages, 10 figures, submitted to Physical Re...             None
4              Table updated and discussion included             None

   journal_ref_id  license_id  field_of_study_id  publication_year  \
0             1.0         NaN                  1              2008
1             2.0         1.0                  1              2011
2             3.0         1.0                  2              2010
3             NaN         NaN                  3              2008
4             4.0         1.0                  4              2009

                                        journal_name volume  issue      pages
0                     Journal of High Energy Physics   2008     02    025-025
1          International Journal of Modern Physics A     26  27n28  4785-4816
2  Philosophical Transactions of the Royal Societ...    368   1933  5695-5706
3                                  Physical Review E     77      5       None
4                            Physical Review Letters    103      6       None

Table: dim_title
   title_id                                              title  \
0         1     On the dyon partition function in N=2 theories
1         2       Modeling M-Theory Vacua via Gauged S-Duality
2         3  A model for the emergence of geopolitical divi...
3         4  Renormalized cluster expansion of the microfie...
4         5  Doping Driven ($\pi, 0$) Nesting and Magnetic ...

  refined_publication_title
0                      None
1                      None
2                      None
3                      None
4                      None

Table: dim_journal_ref
   journal_ref_id                                        journal_ref  \
0               1                                  JHEP0802:025,2008
1               2  Int.J.Mod.Phys.A26:4785-4816,2011;\n  Int.J.Mo...
2               3         Phil. Trans. R. Soc. A 2010 368, 5695-5706
3               4                Phys. Rev. Lett. 103, 067001 (2009)
4               5                     Phys. Rev. B 83, 085302 (2011)

  resolved_venue refined_venue
0           None          None
1           None          None
2           None          None
3           None          None
4           None          None

Table: dim_license
   license_id                                       license_type
0           1  http://arxiv.org/licenses/nonexclusive-distrib...
1           2  http://creativecommons.org/licenses/publicdomain/
2           3  http://creativecommons.org/licenses/by-nc-sa/3.0/
3           4        http://creativecommons.org/licenses/by/3.0/

Table: dim_field_of_study
   field_of_study_id                        field_name
0                  1               High Energy Physics
1                  2                Nonlinear Sciences
2                  3  Mathematics and Computer Science
3                  4          Condensed Matter Physics
4                  5                   Quantum Physics

Table: publication_author_junction
                  publication_id  author_id
0  10.1088/1126-6708/2008/02/025          1
1      10.1142/S0217751X11054693          2
2         10.1098/rsta.2010.0263          3
3     10.1103/PhysRevE.77.056409          4
4     10.1103/PhysRevE.77.056409          5

Table: dim_authors
   author_id      author_name gender
0          1   Justin R David   male
1          2     EIJI KONISHI   male
2          3   M. N. Kuperman   male
3          4  H. B. Nersisyan   male
4          5    D. A. Osipyan   male

## Questions

In [132]:
# Get detailed information for each publication, including a list of authors
query = '''
SELECT 
    fact_publications.publication_id, 
    dim_title.title, 
    STRING_AGG(dim_authors.author_name, ', ') AS authors,
    dim_field_of_study.field_name AS field_of_study,
    fact_publications.publication_year,
    dim_journal_ref.journal_ref,
    fact_publications.journal_name,
    fact_publications.volume,
    fact_publications.issue,
    fact_publications.pages
FROM public."fact_publications"
JOIN public."publication_author_junction" ON fact_publications.publication_id = publication_author_junction.publication_id
JOIN public."dim_authors" ON publication_author_junction.author_id = dim_authors.author_id
JOIN public."dim_title" ON fact_publications.title_id = dim_title.title_id
JOIN public."dim_field_of_study" ON fact_publications.field_of_study_id = dim_field_of_study.field_of_study_id
LEFT JOIN public."dim_journal_ref" ON fact_publications.journal_ref_id = dim_journal_ref.journal_ref_id
GROUP BY fact_publications.publication_id, dim_title.title, dim_field_of_study.field_name, dim_journal_ref.journal_ref
ORDER BY fact_publications.publication_id;
'''
pd.read_sql(query, engine)

,publication_id,title,authors,field_of_study,publication_year,journal_ref,journal_name,volume,issue,pages
0,10.1002/pssb.200945305,Lower current-driven exchange switching thresh...,"S. G. Chigarev, E. M. Epshtein, P. E. Zilberman",Condensed Matter Physics,2010.0,None,physica status solidi (b),247,2,325-328
1,10.1002/qua.22715,Mini-bandstructure tailoring in pi-conjugated ...,"C. A. Mujica‐Martínez, J. C. Arce",Condensed Matter Physics,2010.0,International Journal of Quantum Chemistry 110...,International Journal of Quantum Chemistry,110,13,2532-2540
2,10.1007/978-3-642-13731-0_14,Minimum and maximum against k lies,"Yoshio Okamoto, Philipp Zumstein, Jiří Matouše...",Mathematics and Computer Science,2010.0,None,Lecture Notes in Computer Science,None,None,139-149
3,10.1007/978-3-642-21581-0_5,On variables with few occurrences in conjuncti...,"Oliver Kullmann, Xishun Zhao",Mathematics and Computer Science,2011.0,"SAT 2011, LNCS 6695, page 33-46",Theory and Applications of Satisfiability Test...,None,None,33-46
4,10.1007/978-90-481-9195-6_16,Phase field modeling of nonlinear material beh...,"C. Denoual, L. Truskinovsky, Y.-P. Pellegrini",Condensed Matter Physics,2010.0,"In K. Hackl (ed.), IUTAM Symposium on Variatio...",IUTAM Symposium on Variational Concepts with A...,None,None,209-220
...,...,...,...,...,...,...,...,...,...,...
495,10.4086/toc.2012.v008a013,Span-program-based quantum algorithm for evalu...,"Ben Reichardt, Robert Spalek",Quantum Physics,2012.0,"Theory of Computing, 8(13): 291-319, 2012",Theory of Computing,8,1,291-319
496,10.4153/CMB-2011-127-8,Multiplicity free Jacquet modules,"Dmitry Gourevitch, Avraham Aizenbud",Mathematics and Computer Science,2012.0,Can. Math. Bull. 55 (2012) 673-688,Canadian Mathematical Bulletin,55,4,673-688
497,10.4171/GGD/162,"On the Surjectivity of Engel Words on PSL(2,q)","Shelly Garion, Tatiana Bandman, Fritz Grunewald",Mathematics and Computer Science,2012.0,"Groups, Geometry and Dynamics 6 (2012), 409-439","Groups, Geometry, and Dynamics",6,3,409-439
498,10.4204/EPTCS.39.7,IMITATOR II: A Tool for Solving the Good Param...,Étienne André,Mathematics and Computer Science,2010.0,"EPTCS 39, 2010, pp. 91-99",Electronic Proceedings in Theoretical Computer...,39,None,91-99
499,10.4204/EPTCS.5.3,Dynamic Demand-Capacity Balancing for Air Traf...,"Pierre Flener, Farshid Hassani Bijarbooneh, Ju...",Mathematics and Computer Science,2009.0,"EPTCS 5, 2009, pp. 27-40",Electronic Proceedings in Theoretical Computer...,5,None,27-40

In [133]:
# How many publications were there each year?
query = '''
SELECT publication_year, COUNT(*) AS publication_count
FROM public."fact_publications"
WHERE publication_year IS NOT NULL
GROUP BY publication_year
ORDER BY publication_year;
'''
pd.read_sql(query, engine)

   publication_year  publication_count
0              2006                  4
1              2007                 33
2              2008                120
3              2009                129
4              2010                123
5              2011                 69
6              2012                 11
7              2013                  4
8              2014                  1
9              2016                  2

In [134]:
# Who are the top 5 most frequent publishers (submitter)?
query = '''
SELECT dim_submitter.submitter_name, COUNT(*) AS publication_count
FROM public."fact_publications"
JOIN public."dim_submitter" ON fact_publications.submitter_id = dim_submitter.submitter_id
GROUP BY dim_submitter.submitter_name
ORDER BY publication_count DESC
LIMIT 5;
'''
pd.read_sql(query, engine)

     submitter_name  publication_count
0           Hong Li                  2
1  Michael Pawellek                  2
2  Brant M. Johnson                  1
3      Yves Deville                  1
4          Keji Lai                  1

In [135]:
# Which publications are in the field of 'High Energy Physics'?
query = '''
SELECT fact_publications.publication_id, dim_title.title
FROM public."fact_publications"
JOIN public."dim_field_of_study" ON fact_publications.field_of_study_id = dim_field_of_study.field_of_study_id
JOIN public."dim_title" ON fact_publications.title_id = dim_title.title_id
WHERE dim_field_of_study.field_name = 'High Energy Physics';
'''
pd.read_sql(query, engine)

,publication_id,title
0,10.1088/1126-6708/2008/02/025,On the dyon partition function in N=2 theories
1,10.1142/S0217751X11054693,Modeling M-Theory Vacua via Gauged S-Duality
2,10.1007/JHEP11(2010)088,A Note on G-Fluxes for F-theory Model Building
3,10.1016/j.physletb.2008.03.050,Photon and Axion Splitting in an Inhomogeneous...
4,10.1209/0295-5075/81/61002,The complex relation between production and sc...
...,...,...
92,10.1103/PhysRevD.76.065006,Unparticle physics effects in B_s mixing
93,10.1088/0264-9381/27/21/215012,Self-force of a point charge in the space-time...
94,10.1103/PhysRevD.78.054504,Perturbative determination of $c_{SW}$ for pla...
95,10.1088/1751-8113/42/4/045404,Quantum mass correction for the twisted kink
96,10.1016/j.physletb.2010.02.045,Measurement of isolated photon production in d...

In [136]:
# Which authors have the most publications?
query = '''
SELECT dim_authors.author_name, COUNT(*) AS publication_count
FROM public."publication_author_junction"
JOIN public."dim_authors" ON publication_author_junction.author_id = dim_authors.author_id
GROUP BY dim_authors.author_name
ORDER BY publication_count DESC;
'''
pd.read_sql(query, engine)

                 author_name  publication_count
0                                             5
1                    unknown                  4
2                    P. Wang                  4
3                  P. Giommi                  3
4                 J. H. Kang                  3
...                      ...                ...
4541             O. Volynets                  1
4542  S. di Serego Alighieri                  1
4543             J. Schwartz                  1
4544               S. Pisano                  1
4545                M. Bache                  1

[4546 rows x 2 columns]

In [137]:
# How many publications do not have a specified license?
query = '''
SELECT COUNT(*) AS publications_without_license
FROM public."fact_publications"
WHERE license_id IS NULL;
'''
pd.read_sql(query, engine)

   publications_without_license
0                            98

In [138]:
# How many publications are there in each journal?
query = '''
SELECT journal_name, COUNT(*) AS publication_count
FROM public."fact_publications"
WHERE journal_name IS NOT NULL
GROUP BY journal_name
ORDER BY publication_count DESC;
'''
pd.read_sql(query, engine)

                                          journal_name  publication_count
0                                    Physical Review B                 41
1                            The Astrophysical Journal                 41
2                                    Physical Review D                 30
3                         Astronomy &amp; Astrophysics                 26
4                              Physical Review Letters                 24
..                                                 ...                ...
145             IEEE Transactions on Signal Processing                  1
146                     Groups, Geometry, and Dynamics                  1
147                     Canadian Mathematical Bulletin                  1
148  International Journal of Geometric Methods in ...                  1
149    Proceedings of the National Academy of Sciences                  1

[150 rows x 2 columns]

In [139]:
# How many publications are there for each license type?
query = '''
SELECT dim_license.license_type, COUNT(*) AS publication_count
FROM public."fact_publications"
JOIN public."dim_license" ON fact_publications.license_id = dim_license.license_id
GROUP BY dim_license.license_type;
'''
pd.read_sql(query, engine)

                                        license_type  publication_count
0  http://creativecommons.org/licenses/publicdomain/                  7
1        http://creativecommons.org/licenses/by/3.0/                  1
2  http://creativecommons.org/licenses/by-nc-sa/3.0/                  3
3  http://arxiv.org/licenses/nonexclusive-distrib...                391

In [140]:
# Who are the top authors in each field of study?
query = '''
SELECT dim_field_of_study.field_name, dim_authors.author_name, COUNT(publication_author_junction.author_id) AS publication_count
FROM public."publication_author_junction"
JOIN public."fact_publications" ON publication_author_junction.publication_id = fact_publications.publication_id
JOIN public."dim_authors" ON publication_author_junction.author_id = dim_authors.author_id
JOIN public."dim_field_of_study" ON fact_publications.field_of_study_id = dim_field_of_study.field_of_study_id
GROUP BY dim_field_of_study.field_name, dim_authors.author_name
ORDER BY dim_field_of_study.field_name, publication_count DESC;
'''
pd.read_sql(query, engine)

                      field_name       author_name  publication_count
0     Astronomy and Astrophysics   P. F. Goldsmith                  3
1     Astronomy and Astrophysics      K. M. Menten                  3
2     Astronomy and Astrophysics         P. Giommi                  3
3     Astronomy and Astrophysics        A. W. Chen                  2
4     Astronomy and Astrophysics          F. Longo                  2
...                          ...               ...                ...
4563             Quantum Physics    Pavel Stránský                  1
4564             Quantum Physics     Chang-Woo Lee                  1
4565             Quantum Physics  J. Van der Jeugt                  1
4566             Quantum Physics  P. G. Kevrekidis                  1
4567             Quantum Physics  Valentina Parigi                  1

[4568 rows x 3 columns]

In [141]:
# How has the number of publications in each field of study changed over the years?
query = '''
SELECT publication_year, dim_field_of_study.field_name, COUNT(*) AS publication_count
FROM public."fact_publications"
JOIN public."dim_field_of_study" ON fact_publications.field_of_study_id = dim_field_of_study.field_of_study_id
WHERE publication_year IS NOT NULL
GROUP BY publication_year, dim_field_of_study.field_name
ORDER BY publication_year, dim_field_of_study.field_name;
'''
pd.read_sql(query, engine)

,publication_year,field_name,publication_count
0,2006,Mathematics and Computer Science,3
1,2006,Quantum Physics,1
2,2007,Astronomy and Astrophysics,12
3,2007,Condensed Matter Physics,9
4,2007,General Relativity and Quantum Cosmology,1
5,2007,High Energy Physics,5
6,2007,Mathematics and Computer Science,3
7,2007,Nonlinear Sciences,1
8,2007,Quantum Physics,2
9,2008,Astronomy and Astrophysics,36
10,2008,Condensed Matter Physics,33
11,2008,High Energy Physics,29
12,2008,Mathematics and Computer Science,9
13,2008,Nonlinear Sciences,3
14,2008,Nuclear Physics,4
15,2008,Quantum Physics,6
16,2009,Astronomy and Astrophysics,46
17,2009,Condensed Matter Physics,25
18,2009,General Relativity and Quantum Cosmology,3
19,2009,High Energy Physics,18
20,2009,Mathematics and Computer Science,18
21,2009,Nonlinear Sciences,1
22,2009,Nuclear Physics,3
23,2009,Quantitative Biology,1
24,2009,Quantum Physics,14
25,2010,Astronomy and Astrophysics,31
26,2010,Condensed Matter Physics,29
27,2010,General Relativity and Quantum Cosmology,5
28,2010,High Energy Physics,23
29,2010,Mathematics and Computer Science,20
30,2010,Nonlinear Sciences,1
31,2010,Nuclear Physics,3
32,2010,Quantitative Biology,1
33,2010,Quantum Physics,10
34,2011,Astronomy and Astrophysics,20
35,2011,Condensed Matter Physics,18
36,2011,High Energy Physics,19
37,2011,Mathematics and Computer Science,11
38,2011,Nuclear Physics,1
39,2012,Astronomy and Astrophysics,1
40,2012,Condensed Matter Physics,1
41,2012,High Energy Physics,2
42,2012,Mathematics and Computer Science,6
43,2012,Quantum Physics,1
44,2013,Astronomy and Astrophysics,1
45,2013,Mathematics and Computer Science,2
46,2013,Quantum Physics,1
47,2014,Mathematics and Computer Science,1
48,2016,Mathematics and Computer Science,2

In [142]:
# Which pairs of authors have collaborated the most?
query = '''
SELECT A.author_name AS Author1, B.author_name AS Author2, COUNT(*) AS collaboration_count
FROM public."publication_author_junction" PAJ1
JOIN public."publication_author_junction" PAJ2 ON PAJ1.publication_id = PAJ2.publication_id AND PAJ1.author_id < PAJ2.author_id
JOIN public."dim_authors" A ON PAJ1.author_id = A.author_id
JOIN public."dim_authors" B ON PAJ2.author_id = B.author_id
GROUP BY A.author_name, B.author_name
ORDER BY collaboration_count DESC;
'''
pd.read_sql(query, engine)

                  author1        author2  collaboration_count
0              J. H. Kang    Y. Watanabe                    3
1                B. Golob     A. Sokolov                    3
2            R. Pestotnik    Y. Teramoto                    2
3                T. Uglov     O. Zyukova                    2
4       G. Gomez-Ceballos      P. Renton                    2
...                   ...            ...                  ...
551785                     O. O. Omiwade                    1
551786      I. Lazzizzera      F. Ptohos                    1
551787      T. H. Burnett     P. Lubrano                    1
551788           R. Jesik     G. R. Snow                    1
551789             C. Liu    M. Martínez                    1

[551790 rows x 3 columns]

In [143]:
# Which publications have the highest number of authors?
query = '''
SELECT fact_publications.publication_id, COUNT(publication_author_junction.author_id) AS author_count
FROM public."fact_publications"
JOIN public."publication_author_junction" ON fact_publications.publication_id = publication_author_junction.publication_id
GROUP BY fact_publications.publication_id
ORDER BY author_count DESC
LIMIT 10;
'''
pd.read_sql(query, engine)

                                      publication_id  author_count
0                     10.1103/PhysRevLett.102.121801           600
1                         10.1103/PhysRevD.80.051107           491
2                         10.1103/PhysRevD.83.052004           431
3                     10.1140/epjc/s10052-010-1254-1           345
4                     10.1016/j.physletb.2010.02.045           308
5                        10.1088/0004-637X/720/1/912           174
6  10.1103/PhysRevD.83.051102 10.1103/PhysRevD.83...           146
7                         10.1103/PhysRevD.77.091503           143
8                         10.1103/PhysRevC.80.055203           143
9                       10.1088/0004-637X/698/2/L142            66

In [144]:
# What is the average length of comments in each field of study?
query = '''
SELECT dim_field_of_study.field_name, AVG(LENGTH(fact_publications.comments)) AS avg_comment_length
FROM public."fact_publications"
JOIN public."dim_field_of_study" ON fact_publications.field_of_study_id = dim_field_of_study.field_of_study_id
GROUP BY dim_field_of_study.field_name;
'''
pd.read_sql(query, engine)

                                 field_name  avg_comment_length
0                       High Energy Physics           61.606383
1  General Relativity and Quantum Cosmology           60.888889
2                           Nuclear Physics           51.888889
3          Mathematics and Computer Science           79.569231
4                        Nonlinear Sciences           47.250000
5                  Condensed Matter Physics           43.744898
6                Astronomy and Astrophysics           67.693878
7                           Quantum Physics           42.606061
8                      Quantitative Biology           18.000000

In [145]:
# Which publications are missing journal, volume, issue, or pages information?
query = '''
SELECT publication_id, journal_name, volume, issue, pages
FROM public."fact_publications"
WHERE journal_name IS NULL OR volume IS NULL OR issue IS NULL OR pages IS NULL;
'''
pd.read_sql(query, engine)

,publication_id,journal_name,volume,issue,pages
0,10.1103/PhysRevE.77.056409,Physical Review E,77,5,None
1,10.1103/PhysRevLett.103.067001,Physical Review Letters,103,6,None
2,10.1103/PhysRevB.83.085302,Physical Review B,83,8,None
3,10.1007/JHEP11(2010)088,Journal of High Energy Physics,2010,11,None
4,10.1103/PhysRevLett.105.038302,Physical Review Letters,105,3,None
...,...,...,...,...,...
215,10.1103/PhysRevB.79.161201,Physical Review B,79,16,None
216,10.1214/193940307000000059,Beyond Parametrics in Interdisciplinary Resear...,None,None,62-77
217,10.1103/PhysRevE.80.066105,Physical Review E,80,6,None
218,10.1103/PhysRevE.79.066201,Physical Review E,79,6,None
219,10.4204/EPTCS.39.7,Electronic Proceedings in Theoretical Computer...,39,None,91-99

In [146]:
# How are each submitter's publications spread across different fields of study?
query = '''
SELECT dim_submitter.submitter_name, dim_field_of_study.field_name, COUNT(*) AS publication_count
FROM public."fact_publications"
JOIN public."dim_submitter" ON fact_publications.submitter_id = dim_submitter.submitter_id
JOIN public."dim_field_of_study" ON fact_publications.field_of_study_id = dim_field_of_study.field_of_study_id
GROUP BY dim_submitter.submitter_name, dim_field_of_study.field_name
ORDER BY dim_submitter.submitter_name, publication_count DESC;
'''
pd.read_sql(query, engine)

          submitter_name                  field_name  publication_count
0         ANtonio RIotto  Astronomy and Astrophysics                  1
1     Achille Giacometti    Condensed Matter Physics                  1
2          Adam Kaminski    Condensed Matter Physics                  1
3             Adam Kraus  Astronomy and Astrophysics                  1
4       Adrian Sotomayor         High Energy Physics                  1
..                   ...                         ...                ...
494  Zbigniew Pucha{\l}a             Quantum Physics                  1
495         Zhenhai Wang    Condensed Matter Physics                  1
496       Zhongzhi Zhang    Condensed Matter Physics                  1
497     Zoran Levnaji\'c    Condensed Matter Physics                  1
498           Zsolt Frei  Astronomy and Astrophysics                  1

[499 rows x 3 columns]

In [147]:
# Analyze the gender diversity in publications
query = '''
SELECT fact_publications.publication_id, COUNT(DISTINCT CASE WHEN dim_authors.gender = 'male' THEN publication_author_junction.author_id END) AS male_authors,
COUNT(DISTINCT CASE WHEN dim_authors.gender = 'female' THEN publication_author_junction.author_id END) AS female_authors
FROM public."fact_publications"
JOIN public."publication_author_junction" ON fact_publications.publication_id = publication_author_junction.publication_id
JOIN public."dim_authors" ON publication_author_junction.author_id = dim_authors.author_id
GROUP BY fact_publications.publication_id;
'''
pd.read_sql(query, engine)

                   publication_id  male_authors  female_authors
0          10.1002/pssb.200945305             1               1
1               10.1002/qua.22715             0               0
2    10.1007/978-3-642-13731-0_14             0               0
3     10.1007/978-3-642-21581-0_5             0               0
4    10.1007/978-90-481-9195-6_16             0               0
..                            ...           ...             ...
495     10.4086/toc.2012.v008a013             2               0
496        10.4153/CMB-2011-127-8             0               0
497               10.4171/GGD/162             1               2
498            10.4204/EPTCS.39.7             0               0
499             10.4204/EPTCS.5.3             3               0

[500 rows x 3 columns]

In [148]:
# What are the most referenced journals in the publications?
query = '''
SELECT dim_journal_ref.journal_ref, COUNT(*) AS reference_count
FROM public."fact_publications"
JOIN public."dim_journal_ref" ON fact_publications.journal_ref_id = dim_journal_ref.journal_ref_id
GROUP BY dim_journal_ref.journal_ref
ORDER BY reference_count DESC;
'''
pd.read_sql(query, engine)

                                           journal_ref  reference_count
0                         Astrophys.J.695:552-560,2009                1
1    Annals of Applied Probability 2012, Vol. 22, N...                1
2                            J. Phys. A 42 045404,2009                1
3                             Phys.Rev.D83:055004,2011                1
4                             Phys.Rev.D80:035023,2009                1
..                                                 ...              ...
343                      Rev.Math.Phys.21:615-674,2009                1
344                Phys. Rev. Lett. 103, 067001 (2009)                1
345  Mon. Not. Roy. Astron. Soc., 415, 4, 3462-3472...                1
346                                 JCAP 0906:034,2009                1
347                    J.Phys.Conf.Ser.172:012060,2009                1

[348 rows x 2 columns]

In [149]:
# How has the use of different licenses changed over time?
query = '''
SELECT publication_year, dim_license.license_type, COUNT(*) AS license_count
FROM public."fact_publications"
JOIN public."dim_license" ON fact_publications.license_id = dim_license.license_id
GROUP BY publication_year, dim_license.license_type
ORDER BY publication_year, dim_license.license_type;
'''
pd.read_sql(query, engine)

,publication_year,license_type,license_count
0,2006.0,http://arxiv.org/licenses/nonexclusive-distrib...,3
1,2008.0,http://arxiv.org/licenses/nonexclusive-distrib...,59
2,2008.0,http://creativecommons.org/licenses/by-nc-sa/3.0/,1
3,2008.0,http://creativecommons.org/licenses/publicdomain/,2
4,2009.0,http://arxiv.org/licenses/nonexclusive-distrib...,122
5,2009.0,http://creativecommons.org/licenses/by-nc-sa/3.0/,1
6,2009.0,http://creativecommons.org/licenses/publicdomain/,3
7,2010.0,http://arxiv.org/licenses/nonexclusive-distrib...,118
8,2010.0,http://creativecommons.org/licenses/by-nc-sa/3.0/,1
9,2010.0,http://creativecommons.org/licenses/publicdomain/,2
10,2011.0,http://arxiv.org/licenses/nonexclusive-distrib...,68
11,2011.0,http://creativecommons.org/licenses/by/3.0/,1
12,2012.0,http://arxiv.org/licenses/nonexclusive-distrib...,11
13,2013.0,http://arxiv.org/licenses/nonexclusive-distrib...,4
14,2014.0,http://arxiv.org/licenses/nonexclusive-distrib...,1
15,2016.0,http://arxiv.org/licenses/nonexclusive-distrib...,2
16,NaN,http://arxiv.org/licenses/nonexclusive-distrib...,3

In [150]:
# Find the most common author collaborations in the field of 'Quantum Physics'
query = '''
SELECT 
    A.author_name AS Author1, 
    B.author_name AS Author2, 
    COUNT(*) AS collaboration_count
FROM public."publication_author_junction" PAJ1
JOIN public."publication_author_junction" PAJ2 ON PAJ1.publication_id = PAJ2.publication_id AND PAJ1.author_id < PAJ2.author_id
JOIN public."dim_authors" A ON PAJ1.author_id = A.author_id
JOIN public."dim_authors" B ON PAJ2.author_id = B.author_id
JOIN public."fact_publications" ON PAJ1.publication_id = fact_publications.publication_id
JOIN public."dim_field_of_study" ON fact_publications.field_of_study_id = dim_field_of_study.field_of_study_id
WHERE dim_field_of_study.field_name = 'Quantum Physics'
GROUP BY A.author_name, B.author_name
ORDER BY collaboration_count DESC;
'''
pd.read_sql(query, engine)

                  author1            author2  collaboration_count
0            Corey Trahan       Bill Poirier                    1
1          Guang-Yin Chen      Neill Lambert                    1
2      Alessandro Zavatta   Valentina Parigi                    1
3         Terukazu Kosako  Holger F. Hofmann                    1
4       C. Kalapotharakos     G. Contopoulos                    1
..                    ...                ...                  ...
98              P Aniello       F Ventriglia                    1
99   B. M. Rodríguez-Lara        R. Jáuregui                    1
100       Victor Galitski       S. Das Sarma                    1
101               Hao You      J. D. Franson                    1
102     Tudor D. Stanescu       S. Das Sarma                    1

[103 rows x 3 columns]

In [151]:
# Distribution of publication types (journal, conference, etc.) across different fields of study
query = '''
SELECT 
    fact_publications.publication_type, 
    dim_field_of_study.field_name, 
    COUNT(*) AS count
FROM public."fact_publications"
JOIN public."dim_field_of_study" ON fact_publications.field_of_study_id = dim_field_of_study.field_of_study_id
WHERE fact_publications.publication_type IS NOT NULL
GROUP BY fact_publications.publication_type, dim_field_of_study.field_name
ORDER BY fact_publications.publication_type, dim_field_of_study.field_name;
'''
pd.read_sql(query, engine)

  publication_type                        field_name  count
0         @article  Mathematics and Computer Science      1

In [152]:
# Analyze the gender diversity of authors in each field of study
query = '''
SELECT 
    dim_field_of_study.field_name, 
    COUNT(DISTINCT CASE WHEN dim_authors.gender = 'male' THEN publication_author_junction.author_id END) AS male_authors,
    COUNT(DISTINCT CASE WHEN dim_authors.gender = 'female' THEN publication_author_junction.author_id END) AS female_authors
FROM public."fact_publications"
JOIN public."publication_author_junction" ON fact_publications.publication_id = publication_author_junction.publication_id
JOIN public."dim_authors" ON publication_author_junction.author_id = dim_authors.author_id
JOIN public."dim_field_of_study" ON fact_publications.field_of_study_id = dim_field_of_study.field_of_study_id
GROUP BY dim_field_of_study.field_name;
'''
pd.read_sql(query, engine)

                                 field_name  male_authors  female_authors
0                Astronomy and Astrophysics           110              42
1                  Condensed Matter Physics            73              18
2  General Relativity and Quantum Cosmology             9               4
3                       High Energy Physics           152              63
4          Mathematics and Computer Science            29               5
5                        Nonlinear Sciences             4               2
6                           Nuclear Physics             5               1
7                      Quantitative Biology             0               0
8                           Quantum Physics            22               7